apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: "default"
  labels:
    app: "api-gateway"
data:
  MARKET_PERF_HOST: "market-performance"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
     app: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: "gcr.io/test-project-tp1/api-gateway"
        ports:
        - containerPort: 80
        env:
        - name: "MARKET_PERF_HOST"
          valueFrom:
            configMapKeyRef:
              key: MARKET_PERF_HOST
              name: api-gateway-config
              
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-s-c
  labels:
    app: api-gateway
spec:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP since Ingress will handle access
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-s-n
  labels:
    app: api-gateway
spec:
  type: NodePort  # Changed from LoadBalancer to ClusterIP since Ingress will handle access
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-performance-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: market-performance
  template:
    metadata:
      labels:
        app: market-performance
    spec:
      containers:
      - name: market-performance
        image: gcr.io/test-project-tp1/market-performance
        ports:
        - containerPort: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: market-performance-service
spec:
  type: ClusterIP
  selector:
    app: market-performance
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053
